# Generated by Django 6.1.1 on 2026-09-13 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='workflows.workflow'),
        ),
    ]
