# Generated by Django 6.1.1 on 2026-09-13 18:38

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.contrib.postgres.search import SearchVector
from django.db import migrations


def backfill_search_vector(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Project.objects.update(
        search_vector=SearchVector("name", weight="A") + SearchVector("description", weight="B")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0003_projectexport'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='project',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='project_search_vector_gin'),
        ),
        migrations.RunPython(backfill_search_vector, migrations.RunPython.noop),
    ]
