# Generated by Django 6.1.1 on 2026-09-13 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0001_initial'),
        ('projects', '0002_project_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('task.created', 'Task Created'), ('task.assigned', 'Task Assigned'), ('task.status_changed', 'Task Status Changed'), ('comment.added', 'Comment Added'), ('project_membership.changed', 'Project Membership Changed'), ('workflow.changed', 'Workflow Changed')], max_length=50)),
                ('object_id', models.PositiveBigIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='activity_ac_organiz_25c905_idx'), models.Index(fields=['project', 'created_at'], name='activity_ac_project_be469b_idx'), models.Index(fields=['content_type', 'object_id'], name='activity_ac_content_ee8889_idx')],
            },
        ),
    ]
