# Generated by Django 6.1.1 on 2026-09-13 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_workflow'),
        ('tasks', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='workflow_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='workflows.workflowstate'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'workflow_state'], name='tasks_task_project_ce4c58_idx'),
        ),
    ]
