# Generated by Django 6.1.1 on 2026-09-13 18:38

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.contrib.postgres.search import SearchVector
from django.db import migrations


def backfill_search_vector(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    Task.objects.update(
        search_vector=SearchVector("title", weight="A") + SearchVector("description", weight="B")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_search_vector_and_more'),
        ('tasks', '0002_task_workflow_state_and_more'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='task_search_vector_gin'),
        ),
        # Rows created before this migration have search_vector=NULL until
        # their next save (the signal only fires going forward) — this
        # backfills them in the same migration so search never silently
        # misses pre-existing data.
        migrations.RunPython(backfill_search_vector, migrations.RunPython.noop),
    ]
