from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import permissions, status, viewsets
from rest_framework.decorators import action
from rest_framework.exceptions import PermissionDenied
from rest_framework.filters import OrderingFilter, SearchFilter
from rest_framework.response import Response

from apps.activity.api.serializers import ActivityLogSerializer
from apps.projects.models import Project, ProjectExport, ProjectMembership
from apps.projects.services import ProjectService
from apps.projects.statistics import get_project_statistics
from apps.projects.tasks import export_project_tasks_csv

from .permissions import IsProjectManager
from .serializers import ProjectExportSerializer, ProjectMembershipSerializer, ProjectSerializer

User = get_user_model()


class ProjectViewSet(viewsets.ModelViewSet):
    serializer_class = ProjectSerializer
    permission_classes = [permissions.IsAuthenticated, IsProjectManager]
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = ["organization", "status"]
    search_fields = ["name", "description"]
    ordering_fields = ["created_at", "name"]

    def get_queryset(self):
        if getattr(self, "swagger_fake_view", False):
            return Project.objects.none()
        return (
            Project.objects.filter(memberships__user=self.request.user)
            .select_related("organization", "owner", "workflow")
            .distinct()
        )

    def perform_create(self, serializer):
        organization = serializer.validated_data["organization"]
        try:
            project = ProjectService.create_project(
                organization=organization,
                owner=self.request.user,
                name=serializer.validated_data["name"],
                description=serializer.validated_data.get("description", ""),
            )
        except ValueError as exc:
            raise PermissionDenied(str(exc))
        serializer.instance = project

    @action(detail=True, methods=["get", "post"], url_path="members")
    def members(self, request, pk=None):
        project = self.get_object()
        if request.method == "GET":
            queryset = project.memberships.select_related("user").order_by("user__username")
            page = self.paginate_queryset(queryset)
            serializer = ProjectMembershipSerializer(page, many=True)
            return self.get_paginated_response(serializer.data)
        user = get_object_or_404(User, pk=request.data.get("user_id"))
        role = request.data.get("role", ProjectMembership.Role.DEVELOPER)
        try:
            membership = ProjectService.add_member(project=project, user=user, role=role, actor=request.user)
        except ValueError as exc:
            raise PermissionDenied(str(exc))
        return Response(ProjectMembershipSerializer(membership).data, status=status.HTTP_201_CREATED)

    @action(detail=True, methods=["get"], url_path="activity")
    def activity(self, request, pk=None):
        project = self.get_object()
        queryset = project.activity_logs.select_related("actor", "content_type").order_by("-created_at")
        page = self.paginate_queryset(queryset)
        serializer = ActivityLogSerializer(page, many=True)
        return self.get_paginated_response(serializer.data)

    @action(detail=True, methods=["get"], url_path="statistics")
    def statistics(self, request, pk=None):
        project = self.get_object()
        return Response(get_project_statistics(project=project))

    @action(detail=True, methods=["post"], url_path="export")
    def export(self, request, pk=None):
        project = self.get_object()
        export = ProjectExport.objects.create(project=project, requested_by=request.user)
        # Returns immediately; the CSV is generated by a Celery worker and
        # the requester is notified (Notification, EXPORT_READY) when it's
        # ready — this request never blocks on however long that takes.
        export_project_tasks_csv.delay(export.id)
        return Response(
            ProjectExportSerializer(export, context={"request": request}).data,
            status=status.HTTP_202_ACCEPTED,
        )

    @action(detail=True, methods=["get"], url_path="exports")
    def exports(self, request, pk=None):
        project = self.get_object()
        queryset = project.exports.select_related("requested_by").all()
        page = self.paginate_queryset(queryset)
        serializer = ProjectExportSerializer(page, many=True, context={"request": request})
        return self.get_paginated_response(serializer.data)
