# Generated by Django 6.1.1 on 2026-09-13 18:38

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.contrib.postgres.search import SearchVector
from django.db import migrations


def backfill_search_vector(apps, schema_editor):
    Comment = apps.get_model("comments", "Comment")
    Comment.objects.update(search_vector=SearchVector("body"))


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
        ('tasks', '0002_task_workflow_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='comment_search_vector_gin'),
        ),
        migrations.RunPython(backfill_search_vector, migrations.RunPython.noop),
    ]
