# Generated by Django 6.1.1 on 2026-09-13 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['name']},
        ),
    ]
